config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'routines#index'
  resources :routines do
    resources :comments, only: :create
    collection do
      get 'search'
    end
    collection do
      get 'lifesearch'
    end
    collection do
      get 'trainingsearch'
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, type: '___' },
    { id: 2, type: '生活に関するroutine: 衣類・化粧に関して' },
    { id: 3, type: '生活に関するroutine: 食べ物・飲み物に関して' },
    { id: 4, type: '生活に関するroutine: 住まいのお手入れに関して' },
    { id: 5, type: '鍛えるためのroutine: 心を鍛える' },
    { id: 6, type: '鍛えるためのroutine: 技を鍛える' },
    { id: 7, type: '鍛えるためのroutine: 体を鍛える' }
  ]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :routine
  belongs_to :user

  validates :text, presence: true, length: { maximum: 50 }
end

app/models/routine.rb
class Routine < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category
  belongs_to_active_hash :timeframe
  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy

  with_options presence: true do
    validates :name, length: { maximum: 25 }
    validates :image
    validates :description, length: { maximum: 100 }
  end
  with_options presence: true, numericality: { other_than: 1, message: 'Select' } do
    validates :category_id
    validates :timeframe_id
  end

  def self.search(search)
    if search != ""
      Routine.where('name LIKE(?)', "%#{search}%")
    else
      Routine.all
    end
  end

  def self.lifesearch
    Routine.where(category_id: 2..4)
  end

  def self.trainingsearch 
    Routine.where(category_id: 5..7)
  end

end

app/models/timeframe.rb
class Timeframe < ActiveHash::Base
  self.data = [
    { id: 1, type: '___' },
    { id: 2, type: '平日: 朝方' },
    { id: 3, type: '平日: 昼時' },
    { id: 4, type: '平日: 夕方' },
    { id: 5, type: '平日: 夜中' },
    { id: 6, type: '休日: 朝方' },
    { id: 7, type: '休日: 昼時' },
    { id: 8, type: '休日: 夕方' },
    { id: 9, type: '休日: 夜中' },
    { id: 10, type: '特に決まっていない' }
  ]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX

  validates :nickname, length: { maximum: 6 }, presence: true
  
  has_many :routines
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/routines/#{comment.routine.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, routine_id: params[:routine_id])
  end
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  before_action :move_to_index, except: :index

  def index
    @routines = Routine.order('created_at DESC')
    @newroutine = Routine.last
  end

  def new
    @routine = Routine.new
  end

  def create
    @routine = Routine.new(routine_params)
    if @routine.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @routine = Routine.find(params[:id])
    @comment = Comment.new
    @comments = @routine.comments.includes(:user)
  end

  def edit
    @routine = Routine.find(params[:id])
  end

  def update
    @routine = Routine.find(params[:id])
    if @routine.update(routine_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @routine = Routine.find(params[:id])
    @routine.destroy
    redirect_to root_path
  end

  def search
    @routines = Routine.search(params[:keyword])
  end

  def lifesearch
    @routines = Routine.lifesearch.order('created_at DESC')
  end

  def trainingsearch
    @routines = Routine.trainingsearch.order('created_at DESC')
  end
  
  private

  def routine_params
    params.require(:routine).permit(:name, :image, :description, :category_id, :timeframe_id).merge(user_id: current_user.id)
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @nickname = current_user.nickname
    @routines = current_user.routines
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>for_Tune</title>
    <!-- 文字コード・画面表示の設定 -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">

    <!-- Bootstrap CSSの読み込み -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all'%>

    <!-- jQuery,Popper.js,Bootstrap JS-->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    <!-- routine削除機能のための記述 -->
    <%= javascript_pack_tag 'application' %>
    <%= csrf_meta_tag %>
  </head>

  <body>
    <%= yield %>
  </body>

</html>

app/views/routines/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/routines/_footer.html.erb
<footer>

<div class='routine-btn'>
  <a href="/routines/new">
    <button type="button" class="btn btn-primary btn-lg">routineを投稿する</button>
  </a>
</div>

<div class='footer'>
  <p>© for_Tune</p>
</div>

</footer>

app/views/routines/_header.html.erb
<header>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a href="/" style="color:#000001;text-decoration:none">
  <h2><span class="fantasy">for</span>_<span class="Impact">Tune</span><h6>Self-Management tool<h6></h1>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          ユーザーメニュー
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <% if user_signed_in? %>
          <a class="dropdown-item" href="/users/(current_user.id)">マイページ</a>
          <a class="dropdown-item" href="/users/sign_out">ログアウト</a>
        <% else %>
          <a class="dropdown-item" href="/users/sign_in">ログイン</a>
          <a class="dropdown-item" href="/users/sign_up">新規登録</a>
        <% end %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          カテゴリー検索
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/routines/lifesearch">生活に関するroutine</a>
          <a class="dropdown-item" href="/routines/trainingsearch">鍛えるためのroutine</a>
        </div>
      </li>
    </ul>
    <%= form_with(url: search_routines_path, local: true, method: :get, class: "form-inline my-2 my-lg-0") do |form| %>
      <%= form.text_field :keyword, placeholder: "routine名から検索する", class: "form-control mr-sm-2" %>
      <%= form.submit "search", class: "btn btn-outline-success my-2 my-sm-0" %>
    <% end %>
  </div>
  </nav>

</header>

app/views/routines/edit.html.erb
<%= render "header" %>

<%= form_with model: @routine, url: routine_path(@routine.id), local: true do |f| %>
  <%= render 'error_messages', model: f.object %>
  <div class="form-group">
    <label for="exampleFormControlFile1">Photos in routine</label>
    <%= f.file_field :image, class:"form-control-file", id:"exampleFormControlFile1" %>
  </div>
  <div class="form-group">
    <label for="exampleFormControlInput1">What is routine?</label>
    <%= f.text_area :name, class:"form-control", id:"exampleFormControlInput1", placeholder:"Routine work" %>
  </div>
  <div class="form-group">
    <label for="exampleFormControlSelect1">Category select</label>
    <%= f.collection_select(:category_id, Category.all, :id, :type, {}, {class:"form-control", id:"exampleFormControlSelect1"}) %>
  </div>
  <div class="form-group">
    <label for="exampleFormControlSelect2">Timeframe select</label>
    <%= f.collection_select(:timeframe_id, Timeframe.all, :id, :type, {}, {class:"form-control", id:"exampleFormControlSelect2", size:10}) %>
  </div>
  <div class="form-group">
    <label for="exampleFormControlTextarea1">Description</label>
    <%= f.text_area :description, class:"form-control", id:"exampleFormControlTextarea1", rows:"5" %>
  </div>
  <%= f.submit "submit", class:"send" %>
<% end %>

app/views/routines/index.html.erb
<%= render "header" %>

<%# 画面上部のスライダー部分 %>
<% if @newroutine.present? %>
  <div class="newroutine">
    <%= link_to image_tag(@newroutine.image, class: "routine-img"), routine_path(@newroutine.id) %>
    <div class="newroutine-text">
      <h6 class="newroutine-logo">New routine !!</h6>
      <h4 class="newroutine-name"><%= @newroutine.name %></h4>
    </div>  
  </div>
<% end %>

<!-- カード -->
<div class="card">
  <h2 class= "check-title">みんなのroutine</h2>
  <ul class='routine-lists'>
    <% if @routines.present? %>
      <% @routines.each do |routine| %>
        <li class='routine'>
          <div class="routine-img-content">
            <%= link_to image_tag(routine.image, class: "routine-img"), routine_path(routine.id) %>
            <h5 class="routine-name"><%= routine.name %></h5>        
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>          
</div>

<%= render "footer" %>

app/views/routines/lifesearch.html.erb
<%= render "header" %>

<!-- カード -->
<div class="card">
  <h2 class= "check-title">search-routine</h2>
  <ul class='routine-lists'>
    <% if @routines.present? %>
      <% @routines.each do |routine| %>
        <li class='routine'>
          <div class="routine-img-content">
            <%= link_to image_tag(routine.image, class: "routine-img"), routine_path(routine.id) %>
            <h5 class="routine-name"><%= routine.name %></h5>        
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>          
</div>

<%= render "footer" %>

app/views/routines/new.html.erb
<%= render "header" %>

<%= form_with model: @routine, url: routines_path, local: true do |f| %>
  <%= render 'error_messages', model: f.object %>
  <div class="form-group">
    <label for="exampleFormControlFile1">Photos in routine</label>
    <%= f.file_field :image, class:"form-control-file", id:"exampleFormControlFile1" %>
  </div>
  <div class="form-group">
    <label for="exampleFormControlInput1">What is routine?</label>
    <%= f.text_area :name, class:"form-control", id:"exampleFormControlInput1", placeholder:"Routine work" %>
  </div>
  <div class="form-group">
    <label for="exampleFormControlSelect1">Category select</label>
    <%= f.collection_select(:category_id, Category.all, :id, :type, {}, {class:"form-control", id:"exampleFormControlSelect1"}) %>
  </div>
  <div class="form-group">
    <label for="exampleFormControlSelect2">Timeframe select</label>
    <%= f.collection_select(:timeframe_id, Timeframe.all, :id, :type, {}, {class:"form-control", id:"exampleFormControlSelect2", size:10}) %>
  </div>
  <div class="form-group">
    <label for="exampleFormControlTextarea1">Description</label>
    <%= f.text_area :description, class:"form-control", id:"exampleFormControlTextarea1", rows:"5" %>
  </div>
  <%= f.submit "submit", class:"send" %>
<% end %>

app/views/routines/search.html.erb
<%= render "header" %>

<!-- カード -->
<div class="card">
  <h2 class= "check-title">search-routine</h2>
  <ul class='routine-lists'>
    <% if @routines.present? %>
      <% @routines.each do |routine| %>
        <li class='routine'>
          <div class="routine-img-content">
            <%= link_to image_tag(routine.image, class: "routine-img"), routine_path(routine.id) %>
            <h5 class="routine-name"><%= routine.name %></h5>        
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>          
</div>

<%= render "footer" %>

app/views/routines/show.html.erb
<%= render "header" %>

<div class="routine-show">
  <%= image_tag @routine.image %>
  <%= @routine.name %>
  <%= @routine.description %>
  <%= @routine.category.type %>
  <%= @routine.timeframe.type %>
</div>

<% if current_user.id == @routine.user_id %>
  <%= link_to 'routineの編集', edit_routine_path(@routine.id), method: :get, class: "routine-red-btn" %>
  <%= link_to 'routineの削除', routine_path(@routine.id), method: :delete, class: "routine-red-btn" %>
<% end %>

<div class="container">
  <%= form_with(model: [@routine, @comment], local: true) do |f| %>
    <%= f.text_area :text, placeholder: "コメントする", rows: "3" %>
    <%= f.submit "SEND" %>
  <% end %>
  <div class="comments">
    <h4>＜コメント一覧＞</h4>
    <% if @comments %>
      <% @comments.reverse_each do |comment| %>
        <p>
          <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
          <%= comment.text %>
        </p>
      <% end %>
    <% end %>
  </div>
</div>

<%= render "footer" %>

app/views/routines/trainingsearch.html.erb
<%= render "header" %>

<!-- カード -->
<div class="card">
  <h2 class= "check-title">search-routine</h2>
  <ul class='routine-lists'>
    <% if @routines.present? %>
      <% @routines.each do |routine| %>
        <li class='routine'>
          <div class="routine-img-content">
            <%= link_to image_tag(routine.image, class: "routine-img"), routine_path(routine.id) %>
            <h5 class="routine-name"><%= routine.name %></h5>        
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>          
</div>

<%= render "footer" %>

app/views/users/show.html.erb
<%= render "routines/header" %>

<!-- カード -->
<div class="card">
  <h2 class= "check-title">あなたのroutine</h2>
  <ul class='routine-lists'>
    <% if @routines.present? %>
      <% @routines.each do |routine| %>
        <li class='routine'>
          <div class="routine-img-content">
            <%= link_to image_tag(routine.image, class: "routine-img"), routine_path(routine.id) %>
            <h5 class="routine-name"><%= routine.name %></h5>        
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>          
</div>

<%= render "routines/footer" %>